DROP TABLE IF EXISTS logins;

CREATE TABLE logins (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    pass TEXT NOT NULL
);